networks:
  internal:
    driver: bridge

services:
  nginx:
    image: 'nginx'
    container_name: 2dit_laravel_test-nginx
    networks:
      - internal
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www/2dit_laravel_test
    links:
      - php

  php:
    image: 'php:8.3-fpm'
    container_name: 2dit_laravel_test-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    networks:
      - internal
    volumes:
      - .:/var/www/2dit_laravel_test
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: 'mysql'
    container_name: 2dit_laravel_test-mysql
    networks:
      - internal
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ./docker/mysql:/usr/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_TCP_PORT: ${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping --user=${DB_USERNAME} --password=${DB_PASSWORD} --silent" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
